### ISSUE TITLE
rollup chinese translation

### ISSUE THREAD

**Issue by lcxfs1991** [rollup/rollupjs.org#60]
Dear Rich,

Thanks for your hard work on rollup. We have been watching it for a few months and finally tried it last week. It does have advantage in developing js library/framework over other bundling tools.  

My friend @dear-lizhihua and I are planning to translate the doc into Chinese.  We have experience in translating webpack and make it deploy automatically. (we are running webpack-china now). We can also build [rollup-china](https://github.com/rollup-china). 

Looking forward to your reply.

[My twitter](https://twitter.com/lcxfs1991)

Lee

**Comment by Rich-Harris** [comment]
Hey — thanks so much! This is really awesome. Here's what I'm thinking: rather than creating a separate website, it would be less work for everyone if rollupjs.org itself supported multiple languages. That way, there's no need to keep the code in sync, just the markdown files.

I'm going to play around a bit and see if we can replace `src/guide` with `guide/en`, so that `en` (i.e. English) is just the default. Then we can add `guide/zh` and so on, and someone could get Chinese documentation by visiting rollupjs.org/zh.

Then if someone else wanted to translate the docs to, say, French, they could just add `guide/fr` and so on. We can add a language menu as well.

Does that sound reasonable? If so I'll get to work on that, and once it's ready I can add you and @dear-lizhihua as collaborators on this repo.

**Comment by lcxfs1991** [comment]
That would be great. Yeah please also add @dear-lizhihua as collaborators. Thank you so much!

**Comment by Rich-Harris** [comment]
Great! Have sent you both invites. The first couple of translated sections are now live at https://rollupjs.org/zh — committing new translations to master (you could even use the [web interface](https://github.com/rollup/rollupjs.org/edit/master/guide/zh/01-creating-your-first-bundle.md)!) will cause it to redeploy automatically thanks to Travis CI. Thanks!

**Comment by lcxfs1991** [comment]
Great, thanks! We will make more prs when we get back from Labor's Holiday.
